lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .gitignore
  nextflow_config:
    - params.input
  template_strings:
    - assets/mcmicro_metro.pdf
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: TBD
  description: Whole-slide multiplexed microscopy image analysis
  force: false
  is_nfcore: true
  name: mcmicro
  org: nf-core
  outdir: .
  version: 2.0.0
