lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .gitignore
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  nextflow_config:
    - params.input
  template_strings:
    - assets/mcmicro_metro.pdf
  container_configs: False
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Alex Barberá Mourelle, Robert Young and Jeremy Muhlich
  description: Whole-slide multiplexed microscopy image analysis
  force: false
  is_nfcore: true
  name: mcmicro
  org: nf-core
  outdir: .
  version: 2.0.0
