name: omextractor
description: Extract OME tags and store them into a xml file.
keywords:
  - OME tags
  - bioinformatics tools
tools:
  - bftools:
      description: |
        Suite of tools to handle several imaging protocols.
      homepage: https://www.openmicroscopy.org/bio-formats/
      documentation: https://www.openmicroscopy.org/bio-formats/
      licence: ["GPL-2.0"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - image:
        type: file
        description: |
          Registration image
output:
  - xml:
      - "ome.xml":
          type: file
          description: OME xml tags
          pattern: "ome.xml"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@AlexBarbera"
maintainers:
  - "@AlexBarbera"
